### osquery
GET http://localhost:8888/actuator/osquery

### osquery schema
GET http://localhost:8888/actuator/osquery/etc_hosts?format=csv

### osquery schema with columns
GET http://localhost:8888/actuator/osquery/etc_hosts(address,hostnames)

###
